# Travis CI build config for Salad

language: c

compiler:
  - clang
  - gcc

# Below is a workaround for the "unknown CMake command: target_include_directories" error.
# This feature was added in more recent versions of CMake.
sudo: false
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data

script:
  - cmake . && make

notifications:
  email: false
  irc:
    - "irc.dilley.me#sysadmininkudzu"
    - "chat.freenode.net#libsalad"
    - "irc.oftc.net#salad"
