# Travis CI build config for Salad

language: c

compiler:
  - clang
  - gcc

script:
  - cmake . && make

notifications:
  email: false
  irc:
    - "irc.dilley.me#sysadmininkudzu"
    - "chat.freenode.net#libsalad"
    - "irc.oftc.net#salad"
